# Generated by Django 2.0.5 on 2018-05-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180531_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Time',
            new_name='Date',
        ),
    ]
