# Generated by Django 2.0.5 on 2018-05-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_article_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Order',
        ),
    ]
