# Generated by Django 2.0.5 on 2018-06-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180531_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('View', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='Quantity',
        ),
    ]
